### ISSUE TITLE
Conversation connection ended suddenly

### ISSUE THREAD

**Issue by shunyh** [microsoft/BotFramework-DirectLineJS#275] opened 2020-03-24 09:49 UTC
Hi Team,

The conversation connection suddenly ended when the customer chatting with Bot, and it can't be re-connected. 

I didn't get any error from our service, could you help to verify is there anything wrong from Bot-DirectLines?

![image](https://user-images.githubusercontent.com/7311188/77411391-52b27c00-6df7-11ea-8423-561599fd8ea6.png)

ConversationId: 7x3VDp97qzwCQB7c9g0CSt-l 
Timestamp: 2020.03.24 16:00:02(China time)

**Comment by anusharavindrar** [comment] 2020-03-25 18:03
@shunyh do you get any error in the Channel's health tab on Azure? Are you trying to reconnect to a conversation with Enhanced Authentication enabled?

**Comment by shunyh** [comment] 2020-03-26 02:29
@anusharavindrar 

Thanks for your response.

There were several customers chatting with the bot at the same time, but this is the only one that encountered this problem. 

I tried to chat with the bot and it went well when a customer reported this problem to my team, because this issue occurred in Production. Fortunately, the other customers didn't get this problem.   

Checked the status of the Channel' health, all the errors were Gateway timeout. It looks like this is not the root cause of the above exception, the timestamp didn't match.
  
![image](https://user-images.githubusercontent.com/7311188/77603301-b0a3a880-6f4a-11ea-9b75-d1bd7f20a0f4.png)

As you can see from the screenshot, no errors found at **2020.03.24 16:00:02(China time)**.

**Comment by shunyh** [comment] 2020-03-30 06:44
@anusharavindrar is there any progress?

**Comment by anusharavindrar** [comment] 2020-03-30 16:32
@shunyh Are you trying to reconnect to a conversation with Enhanced Authentication enabled? Also, can you provide the MicrosoftAppId, BotHandle, and UTC timestamp of when this exactly happened?

**Comment by shunyh** [comment] 2020-03-31 08:14
@anusharavindrar 

I suggested the customer create a new chat session with the new conversation Id, I didn't enable the Enhanced Authentication and I didn't know how to enable it either.

MicrosoftAppId: b803e03d-9f53-4f89-a9af-cede7b0e6092

UTC timestamp: 2020.03.24 08:00:02

BTW, what is BotHandle?

**Comment by anusharavindrar** [comment] 2020-03-31 19:50
@shunyh the bot handle is found below the display name under the bot settings on Azure.
![image](https://user-images.githubusercontent.com/48731427/78068910-15497380-734e-11ea-9dd0-ffbabef068b7.png)

**Comment by shunyh** [comment] 2020-04-03 06:49
@anusharavindrar 

Thank you.

The Bot handle is **chatbot-prod-ea**.

![image](https://user-images.githubusercontent.com/7311188/78332251-36160100-75ba-11ea-948b-cffa06d6da20.png)

**Comment by anusharavindrar** [comment] 2020-04-07 17:17
@shunyh thanks for the above details. I will update the thread soon with my findings.

**Comment by shunyh** [comment] 2020-04-09 06:57
@anusharavindrar  thank you in advance.

**Comment by shunyh** [comment] 2020-04-13 06:06
Hi@anusharavindrar  

Any updates?

**Comment by anusharavindrar** [comment] 2020-04-13 22:29
@shunyh I checked the logs on our end, but could not find any errors for the given timestamp. I am guessing this to be related to the token expiration. The Direct Line client is responsible for refreshing the token and if the Cx's Direct Line client does not refresh the token then it will expire.

Did the customer again face the same issue after creating a new chat session with new conversation ID?

**Comment by shunyh** [comment] 2020-04-14 06:21
@anusharavindrar 
The customer went well after creating a new conversation. It doesn't occur again, but if we can dig the root cause that would be better.

**Comment by anusharavindrar** [comment] 2020-04-16 00:19
@shunyh Glad that its working for the Cx after creating a new chat session. Since I could not find any errors with the logs for the particular timestamp, I cannot be exact about what might be causing it, although I am guessing its mostly due to token expiration. 

Attaching #251 and #191 for related issues.

I will be closing the issue for now. Please feel free to reopen the issue if the Cx faces the issue again.

**Comment by gabog** [comment] 2020-05-27 18:27
Reopening as this was reported again in #283.

**Comment by anusharavindrar** [comment] 2020-06-09 19:08
@shunyh, can you provide the MicrosoftAppId, BotHandle, and UTC timestamp of when this exactly happened so we can investigate on our end?

**Comment by shunyh** [comment] 2020-06-19 09:00
@anusharavindrar 

ConversationId : KrpeUD3Ii74640PV07MTGA-l
Timestamp(UTC): 2020.05.26 08:10:38 --2020.05.26 08:25:38
MicrosoftAppId: b803e03d-9f53-4f89-a9af-cede7b0e6092
The Bot handle: chatbot-prod-ea.

**Comment by anusharavindrar** [comment] 2020-06-23 18:27
@shunyh, thanks for the details. We will investigate it on our end with the provided details.

**Comment by cleemullins** [comment] 2020-07-06 18:32
@anusharavindrar, can you please provide an update?

**Comment by anusharavindrar** [comment] 2020-07-06 18:39
Adding @bwamie to help further investigate the issue.

**Comment by bwamie** [comment] 2020-07-21 19:50
Bot Service only keeps logs for 30 days. Unfortunately it may not be possible to investigate the cause. I recommend closing it and opening it for investigation when it reoccur.

**Comment by munozemilio** [comment] 2020-07-21 21:31
Closing this per last comment

**Closed by munozemilio** 2020-07-21 21:31 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by shunyh** [comment] 2020-07-22 02:49
I have lost patience with this question too, and do not expect an answer since it lasts so much time.
