### ISSUE TITLE
Expired token throws an exception

### ISSUE THREAD

**Issue by AntonioFranchinotti** [Microsoft/BotFramework-DirectLineJS#177] opened 2019-04-04 22:28 UTC
Hi!

We have our bot configured with WebSockets, and we are subscribed to the connection status events.

We know our subscription is working since we receive the `2` status (for Conversation online) and we send data to the bot with no problem.

If we suspend or hibernate the computer with the browser open, and then try to interact to the bot after more than 30', webchat.js throws an exception and the bot stops working.

**Comment by compulim** [comment] 2019-04-04 22:35
This is being tracked in #124 and #103.

We have two ways to generate the token:

1. From secret, with a brand new conversation ID
1. From another token, with an existing conversation ID (this is what we call "renew")
   - This can only be done while the former token is still valid (within 30 minutes)

Today, if the token is not renew on time (hibernate), we need to use the secret to generate the token.

But the problem is, we cannot reuse an existing conversation ID while using the secret to generate the token. Channel team is aware of the issue and they are working on this scenario.

Since this is already tracked in another issues, I am closing this for dedupe.

**Closed by compulim** 2019-04-04 22:35 UTC

**Comment by AntonioFranchinotti** [comment] 2019-04-04 22:38
Thanks for the prompt answer @compulim, so the Webchat framwork exception we are seeing is in fact due to the DirectLineJS issue? Had to ask since I've seen

**Comment by compulim** [comment] 2019-04-04 23:20
Yap, it's DirectLineJS issue so I moved it over here. 😄
