### ISSUE TITLE
Connection statuse, 4 not triggered with directline connection

### ISSUE THREAD

**Issue by mrmokilok** [microsoft/BotFramework-DirectLineJS#261] opened 2020-01-23 14:03 UTC
Have subscribed connection status changes (.connectionStatus$.subscribe) with vanilla js. Other statuses get called, but statuse 4 (Failed to connect) doesn't get triggered, when directline connection fails.

## Version
Latest

**Comment by corinagum** [comment] 2020-01-28 03:04
Hi @mrmokilok, looking at the code and running through a Web Chat scenario, if there's any error on `startConversation`, `FailedToConnect` will be thrown. As an example, I entered an incorrect secret into Web Chat and saw the expected behavior.

Could you put a breakpoint on line [545 of DLJS](https://github.com/microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L534-L549) and provide more details about the error you're getting? 
If this scenario doesn't match your repro steps, please provide those repro steps.

**Comment by mrmokilok** [comment] 2020-01-30 10:53
Hi @corinagum I did catch that the error will be thrown and built try catch around webchat initialization for it, as a workaround. I'm currently working on something else completely and unfortunately can't spare time to debug this deeper. 

If I recall correctly, I ran into this with a bot where there is Azure AD login for the bot user. When I 1.) Had logged user in, 2.) logged out from another Microsoft service on another browser tab, 3.) refreshed bot UI page before token has expired (expiring handled separately). Error comes, though only connection user auth has to bot auth, is the settings in bot channel registration. Bot connection should be authenticated, even when user is logged out.

The trouble is that subscribed connection status (botConnection.connectionStatus$.subscribe) doesn't fire, as it does with 1 = Connecting, 2 = Online, 3 = ExpiredToken and 5 = Ended. So, Connection status 4 = FailedToConnect never comes. I believe this is the preferred place to handle it, instead of error handling.

**Comment by clearab** [comment] 2020-02-10 18:19
@corinagum do you have anything additional to add?

**Comment by corinagum** [comment] 2020-02-10 19:33
Hi @mrmokilok , thanks for the extra information. I'll get a repro going and reply back to this thread.

**Comment by carlosscastro** [comment] 2020-02-21 18:07
@corinagum were you able to repro?

**Comment by corinagum** [comment] 2020-02-25 18:10
Hi @carlosscastro, still working on this one.

**Comment by corinagum** [comment] 2020-02-26 17:35
I don't have a repro for this scenario. Being logged in (or logged out) to an AAD account is separate from the bot, as you say, since the bot's authentication has to do with it's ability to communicate with the channel.

Here's my subscribe code for connection status:

```
        directline.connectionStatus$.subscribe({
          error: err => console.error(err),
          next: connectionStatus => {
            console.log(connectionStatus);
          }
        });
```
And below I have the console log receiving status 4. 

![image](https://user-images.githubusercontent.com/14900841/75370258-ab830900-5879-11ea-9bb6-d8aa9dfeb2bf.png)

In the end I'm still receiving the expected connection status of 4 when authentication fails.

I will close this issue as no repro, but if more details come in or other users have a similar experience, we can reopen.

**Closed by corinagum** 2020-02-26 17:35 UTC
Labels: Bot Services, customer-replied-to, customer-reported
