### ISSUE TITLE
Resume conversation after call botConnection.end() 

### ISSUE THREAD

**Issue by rainmakerho** [Microsoft/BotFramework-DirectLineJS#118] opened 2018-05-07 09:02 UTC
I use "samples/backchannel/index.html" to test stop/start conversation.
How to resume conversation after call botConnection.end() ?
Thanks.

**Comment by compulim** [comment] 2018-11-29 18:33
Transferring this one from Web Chat to DirectLineJS.

**Comment by compulim** [comment] 2019-04-02 00:03
Marking as dupe of #124 and resolving it over that uber-bug.

**Closed by compulim** 2019-04-02 00:03 UTC
Labels: 4.4, approved, duplicate, p0, triaged
