### ISSUE TITLE
Error on Members Added "read econnreset"

### ISSUE THREAD

**Issue by BhargavJanardhan** [microsoft/BotFramework-DirectLineJS#298] opened 2020-07-28 17:42 UTC
**Issue :** Error message "read econnreset" is coming in Members Added method.
**Description :** 

- We are using DirectLine to send the messages.

- In the bot service code(**Node JS**), while we are sending welcome message in members added method the above error is coming. Below is the line how we send a welcome message.
**await context.sendActivity(MessageFactory.text(copy.t("welcome")));**

We are not sure what is going wrong and getting failed with this error when we send a message. Can you please help us with this by checking the logs from your end with below details.
App ID: 461494cb-be52-4d6c-af90-2abc2f69dfc2
Timestamp: 2020-07-26T19:16:19.632Z
Conversation ID: We don't have it.

Below attached file is the error log exported from Application Insights.
[Error.xlsx](https://github.com/microsoft/BotFramework-DirectLineJS/files/4990122/Error.xlsx)

Please let us know if this information is helpful or required any more details.

**Comment by stevkan** [comment] 2020-07-29 21:30
Closing as a duplicate of #299.

**Closed by stevkan** 2020-07-29 21:30 UTC
Labels: Bot Services, Support, customer-replied-to, customer-reported

**Comment by BhargavJanardhan** [comment] 2020-07-30 11:33
I am not sure why this has been closed as duplicate though the errors are different.

This is the only one error came in Members added but where as https://github.com/microsoft/BotFramework-DirectLineJS/issues/299 errors came in 3 different places with another error. Hence I would like to reopen this issue.

If you would need more information please let me know
