### ISSUE TITLE
Watermark resetting back to zero within same conversation

### ISSUE THREAD

**Issue by knoppanthony** [microsoft/BotFramework-DirectLineJS#242] opened 2019-10-23 19:14 UTC
We're inconsistently seeing a behavior of the watermark resetting back to 0000000 within the same conversation.

We obtain a stream URL from directLine and open a websocket. Post a few activities, see the watermark increasing on the response. (this is all via a token, not a direct secret)

Sit idle for some amount of time (5-15mins)....post a new activity to the conversation....
See that the response from the post contains a watermark of 0000000, as if its the first activity of the conversation.

This watermark reset seems to prevent our web socket from receiving events. If we post more activities, such that the watermark 'catches up' to the number it was at before it reset....the web socket then seems to begin functioning properly and receiving traffic.

Is this watermark reset expected behavior? 
We don't manipulate the watermark in anyway on the client side.

**Comment by crutkowski-84** [comment] 2019-10-23 20:55
I am on the same team with @knoppanthony and have some additional clarification for this.

I was running some further tests and found that I can reproduce this by using nothing more than the Directline REST API.  Steps to reproduce:

1. Send a REST request to create a new conversation (https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-start-conversation?view=azure-bot-service-4.0).
2. Use the conversation ID and your Directline secret to POST messages to the conversation (https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0).  The response will contain the id property, which will consist of the conversation id and the watermark value concatenated together.
3. Wait 6 minutes.
4. POST another message to the conversation.

The watermark that is part of the id property on the message posted to Directline in step 4 will be reset to 0000000.

**Comment by Jeffders** [comment] 2019-10-24 02:36
Thank you for reporting this issue. I've assigned this issue to myself to look through our Direct Line service code and see what's going on here.

**Comment by knoppanthony** [comment] 2019-10-24 12:55
Thanks @Jeffders, Please let us know if you need any more information. Happy to jump on a call if need be!

**Comment by Jeffders** [comment] 2019-11-06 17:46
@knoppanthony and @crutkowski-84,

Sorry for the delay, but are you still seeing this issue? I tried to reproduce this over the course of several days using both a WebSocket to retrieve messages and also polling for new Activities. In both cases the watermark remained stable (and increasing). The only thing I noticed was that when I send a message from client to bot and the bot responds, on the WebSocket I receive an ActivitySet with a watermark of null for the message I sent form client to bot, but the watermark has a value for the bot to client Activity (in the ActivitySet).

To help me diagnose this further, could you:

1. Verify if this is still an issue
2. Send me some diagnostic details (timestamp/range, botid, and conversationId)
3. Are you looking for the watermark on the resulting ActivitySet, or pulling it off the Activity? The client should be using the watermark it gets from calling GetActivities (via polling) or the ActivitySet received from the WebSocket connection.

Thank you for helping me diagnose this!

**Comment by crutkowski-84** [comment] 2019-11-08 21:20
@Jeffders ,

We are currently unable to reproduce the issue at this time.  We did dig into some logs for the past 2 months to try to determine how frequently this is occurring and we saw that there were large spikes on the following dates: 
- October 4th
- October 7th
- October 22nd 
- October 23rd (the day this issue was opened)

There were also small spikes on October 3rd and October 18th.

Since we cannot reproduce this at the moment, our plan is to wait until we start seeing the issue again, and once we do, we will follow the steps to attempt to reproduce the issue with a simple Echo bot, just to take our bot entirely out of the equation.

Since this is so intermittent, would replying to this thread and tagging you be the fastest way to get in touch with you once we do start seeing the problem again so you can troubleshoot while we are actively seeing the problem?

**Comment by Jeffders** [comment] 2019-11-08 21:28
Yes for sure, that would be great.

Since you do have some logs, can you send me the specific timestamps, botid, and conversation/activity IDs where you saw this?? You can email me at: jeffders at microsoft dot com

Thanks!

**Comment by Jeffders** [comment] 2019-11-12 16:55
Closing the issue for now. Please re-open if you experience this and can send me some telemetry (botid, conversationid, timestamps).

**Closed by Jeffders** 2019-11-12 16:55 UTC
Labels: Bot Services, R7, customer-replied-to, customer-reported
