### ISSUE TITLE
When setting up a conversation token to directline access the name property is not transmitting through to the bot conversation

### ISSUE THREAD

**Issue by xtianus79** [microsoft/BotFramework-DirectLineJS#291] opened 2020-06-24 17:10 UTC
Even though the user > id and userName > name is in the actual token that is created when the get conversation token api is called the bot never receives the name property with the conversation. Only the ID.  

I am passing the name through so I would like to receive it in the bot layer to address the persons information. The id being a token, in my case, is great but I don't have personal information in that SSO token.

**Comment by jwiley84** [comment] 2020-06-25 15:40
Acknowledging here, as I cannot be assigned to GH issues for some reason.

**Comment by stevkan** [comment] 2020-06-26 00:24
Hi @xtianus79, I've been speaking with our service team to identify if this is expected behavior or not. I won't have an update until tomorrow, mid-day, at the earliest.

As a side note, it should be noted that whether you have [enhanced authentication](https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/) enabled in the Direct Line channel for your bot _does_ make a slight difference. If enabled, the User.ID passed into the token is set to secure to prevent the value being changed. If disabled, then both the User.ID and User.Name (i.e. From.ID and From.Name in an activity) can be overwritten.

The current questions are: Is the User.Name property supposed to be secure if DL enhanced authentication is enabled, and should it display in the activity whether enhanced authentication is enabled or not?

**Comment by stevkan** [comment] 2020-06-26 04:40
@xtianus79, I was able to get a response sooner than expected. This behavior is by design. The User.ID is embedded into the token for security reasons to help prevent malicious users from modifying the ID. The User.Name is embedded so it can be accessed by the conversationUpdate that occurs when a direct line connection is initially established before any conversation actually occurs.

The expectation is the Name will be set by the client in each of the proceeding activities. In Web Chat, for instance, the name is set in the `username` property in `window.WebChat.renderWebChat()` and `window.ReactDOM.render( <ReactWebChat [...] />)`.

If you are insistent on using the token's embedded name, then I'd suggest you capture the value during the conversationUpdate and pass it as a parameter in an event, postBack, or some other back to your client where it can be passed in as the From.Name in the following conversation activities.

Hope of help.

Closing this as resolved.

**Closed by stevkan** 2020-06-26 04:40 UTC
Labels: Bot Services, Support, customer-replied-to, customer-reported

**Comment by xtianus79** [comment] 2020-06-26 14:23
@stevkan wait can you reopen this please? The design is awkward. In this statement 
> The User.Name is embedded so it can be accessed by the conversationUpdate that occurs when a direct line connection is initially established before any conversation actually occurs.

Is this available in the bot-framework at the time a user starts a conversation? That is what I am trying to say. Because the way I am interpreting that the conversation start which, has the token appended to the websocket param, is of the correct token but it does not pass the username. It's there but doesn't get passed.  Why? 

Here is the internals of the bot proving this. 

```javascript
{ type: 'message',
     id: 'CWQEmkC5gd36aeMdl23ZXY-6|0000013',
     timestamp: 2020-06-26T14:18:12.740Z,
     serviceUrl: 'https://directline.botframework.com/',
     channelId: 'directline',
     from: { id: '77777777777' },
     conversation: { id: 'CWQEmkC5gd36aeMdl23ZXY-6' },
     recipient:
```

See the from is only the id. Which is great but there is no name being passed through. 

Here is the token that is appended to the websocket connection. The username is there. But it doesn't resolve to the bot itself. That is the concern. I am passing it through but it isn't actually being used. 
```javascript
{
  "bot": "xxxxxxx-xxxxxxx-bot",
  "site": "2MnpO8SotMQ",
  "conv": "CWQEmkC5gd36aeMdl23ZXY-6",
  "user": "77777777777",
  "username": "{\"first\":\"Christian\",\"last\":\"Matthew\"}",
  "nbf": 1593180705,
  "exp": 1593180765,
  "iss": "https://directline.botframework.com/",
  "aud": "https://directline.botframework.com/"
}
```

**Comment by dandriscoll** [comment] 2020-06-26 15:00
Hi @xtianus79, there are two different activity types in play here.

The `conversationUpdate` activity type is generated by Direct Line and is sent to your bot. This is why we include the user.name in the token, and this activity should include the user.name, as your client has no way to add the data if it weren't in the token.

The `message` activity type is created by the client (Web Chat or your own client) and sent to Direct Line, and a matching activity is sent to the bot. You should populate all fields in the `message` activity on your own -- this allows you to set the user.name to a different value if the user chooses, without generating a new token. This also provides your client with a complete view of the activity object. If you leave the user.name out when you generate this activity, the client does not have all of the fields used to display the activity.

Something we could consider is adding the user.name field from the token if it's not set in the `message` activity, but that would not help the client maintain a complete object in memory.

**Comment by xtianus79** [comment] 2020-06-28 16:28
@dandriscoll thanks for your reply. I am not too sure about where the conversationUpdate activity takes place compared to the conversation token and just inherently starting a conversation takes place. Also, I am not sure that is what the main over arching point is.  The reason why I bring that up is because I'm just not receiving the payload where I need it to be. 

I think it would help to walk  you down my approach. What I am looking to do is a single sign on approach. Meaning, when a user enters the chat they are expected to have been signed in. In fact, they won't be able to see the chat, or certain dialog routes, until they are signed in or some abstraction thereof such as protected routes to dialogs.   

So how do they sign in? Well when they sign in to the site they get an authorization token, this token is an auth token but not user profile information. This token will be used as the id for conversation essentially bringing in that authentication for the user into the bot. But there's no personal information on that token. That is where the name field comes in. It would allow me to identify the person coming into the chat. 

What I think you're saying is that the message activity cold send this information to the chat on every activity but that is a solid use case and here's why.  

The Id acts, in my mind, correctly it can't mutated and it is the id set by the initiation of the conversation.  So, even if I change it on the message activity it won't change to that conversations id that was assigned from the beginning. I am simply arguing that the name should hold the same effect. Why?

On an incoming payload, and keeping with the SSO theme, the information started with a conversation can be, should be, stored in the conversation state and user profile state. This is where anything should be stored for usage at a later time. Things such as api authorization, name, and other metadata that pertains to that user when they entered into the bot. 

It doesn't make sense to me to obtain a name from a message being sent and then parsing that to apply to a userstate profile data set. 

To your point what I think you were saying at the end is to treat the username / name as the id is when it is not set in the message activity so then you would use it the from the token. That makes sense and is totally a way to do this I guess. 2 things about that. 1. The id is non-mutable, meaning if you change it in the message activity it doesn't change or overwrite what was there already if something was there. This is acceptable as if you took the effort to set it in the token then that should be what it is. The name should IMO work the same way. 

2. 
> That would not help the client maintain a complete object in memory. 
? What does that mean exactly I am confused by that? The bot should be the only place worried about state and memory.

No matter what I would just expect to be able to use the Username / name field I am setting without having to worry about setting it or extracting it other than the token I am setting in the first place.

**Comment by dandriscoll** [comment] 2020-06-29 15:28
Hi @xtianus79 if you're trying to achieve SSO by sending your webpage's token down to the bot, you may choose to send it once, or you may choose to send it on every message.

- If you choose to send it once, you should use the **Event activity** to send it silently in the background.
- If you choose to send it on every Message, you should use the **ChannelData** field, as this is a reserved area that you may use for any of your own data.

I can discuss the reasons why we protect the ID field, why we don't protect the Name field, and why we added Name to the token path, but if I understand what you're trying to achieve, none of these are great fits for your scenario.

**Comment by xtianus79** [comment] 2020-06-30 04:25
@dandriscoll lol yea you might be right as there is a 64 character limit on the id field. Ok, so I am glad to hear there are other outlets for what I am trying to do. The event activity that goes with the conversation start? And if so where would that be picked up exactly (on the bot side?)

I would like to send it once in the background. I think that is the most ideal solution.  For example, I would like to start a conversation, consume user profile data and create their own userprofile data state so when they call upon an API they can authorize against it. 

The ChannelData, is that from the client to the bot service? 

Also, is there a recommended way of sending off a payload through the bot to the client that is not text but rather a payload of data from an api call? I know a place where you can do that but not sure if there is a better recommended way. 

Lastly, is there documentation for the 2 examples you gave above I don't think I have ever read those examples.

**Comment by xtianus79** [comment] 2020-07-01 06:43
@dandriscoll so thank you the event activity will work well. I have a couple questions. 

1. Can you trigger an event that will emit an event back to the client? I.e. fire an api call and wait for result to come back through a sendActivities(event)

2. Can you send an event activity through sendActivities([])? Just wondering if you can trigger a portion of a dialog to send a specific event via type through the sendActivities method. 

as an example 

```javascript
await context.sendActivities([
   { type: 'typing' },
   { type: 'delay', value: 2000 },
{ type: 'event', name: 'somename', value: {value: value},
   { type: 'message', text: 'Hello... How are you?' }
]);
```

**Comment by dandriscoll** [comment] 2020-07-02 19:23
Answers to the questions above:

- Within Direct Line and Web Chat, ChannelData is owned by you (the developer) and works in both directions. ChannelData is a complex JSON object so you can include multiple fields and nested structures. The schema is entirely up to you.
- Yes, you can send Event activities in both directions. Choose a value of the Name field that is specific to your application when you do. ("SendToken" would be OK. Events can have any meaning you want so just use Name to distinguish between them.) This document describes more: https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-backchannel?view=azure-bot-service-3.0
- @tonyanziano do you know if the emulator can send Event activities?

**Comment by xtianus79** [comment] 2020-07-04 16:10
@dandriscoll Awesome!!! This opens up a whole new world. 
@tonyanziano Yes, as of now i see conversation update, typing, ping (<<is that a type) and deleteUserData. But not events.

**Comment by xtianus79** [comment] 2020-07-12 02:35
@tonyanziano is there the ability to send / trigger an event from a local environment?

**Comment by tonyanziano** [comment] 2020-07-13 16:08
Sorry I didn't respond last week, I missed this notification.

Hi, @xtianus79 

There is currently no way to send a custom activity (like an event) from the Emulator other than what is available in the "Conversation" menu item.

However, this is on our radar as it is one of the most requested features right now. You can track the issue here:

https://github.com/microsoft/BotFramework-Emulator/issues/1700
